### ISSUE TITLE
Useful resource

### ISSUE THREAD

**Issue by MrOctopus** [erri120/papyrus-compiler#9]
Here's an additional resource you might find useful: https://github.com/cadpnq/papyrith.
The aforementioned repository is a Papyrus compiler written in Common Lisp.

**Comment by erri120** [comment]
Nice, will add that to the README. Is that compiler for all games or only for one? It looks like it supports structs.

**Comment by MrOctopus** [comment]
As far as I can remember, I believe it was intended to support both versions. Though, I have not looked into the actual implementation to uncover if this was just planned or partly implemented.
